### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by sbeyer**
This pull request fixes the broken links to code.google.com

### CODE REVIEW

**Comment by TPS** [comment]
@KlausW This 1 is super-important.  Would you mind looking over to accept?

If inclined, take a peek @ some of the other PRs, too.

Thanks!

**Comment by sbeyer** [comment]
Updated (rebased to current master), hence ping @klausw

**Comment by klausw** [comment]
Thank you!

**Comment by TPS** [comment]
Thanks @sbeyer & @klausw! 🙇

**Pull request merged**
