### PR TITLE
Add Material Dark theme

### PR DESCRIPTION
**Pull request by PorygonZRocks**
I also have some code for a Material Light theme, but it looks bad (there's some sort of outline around letters that makes it look weird). Uncomment line 387 in strings.xml if anybody wants to test it. 
A few files for some reason went from 755 to 644 permissions, but I have no idea why, or how to undo it. None should have any negative effect, however.

### CODE REVIEW

**Comment by SolarAquarion** [comment]
Can you build a apk?

**Comment by SolarAquarion** [comment]
[javac] Compiling 38 source files to /home/solaraquarion/hackerskeyboard/java/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/solaraquarion/hackerskeyboard/java/src/org/pocketworkstation/pckeyboard/KeyboardSwitcher.java:65: error: cannot find symbol
    [javac] 		R.layout.input_material_dark,
    [javac] 		        ^
    [javac]   symbol:   variable input_material_dark
    [javac]   location: class layout
    [javac] /home/solaraquarion/hackerskeyboard/java/src/org/pocketworkstation/pckeyboard/KeyboardSwitcher.java:66: error: cannot find symbol
    [javac] 		R.layout.input_material_light,
    [javac] 		        ^
    [javac]   symbol:   variable input_material_light
    [javac]   location: class layout
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors
    [javac] 3 warnings

**Comment by PorygonZRocks** [comment]
Oops... I forgot to commit with -a. I'll have to redo it, since I build on my tablet, and have wiped the tablet since working on this. I'm going to close this until I'm done. Sorry about that.

**Comment by PorygonZRocks** [comment]
Manually recoloring all the icons takes a while. If I were to just copy the icons from the AOSP source, how would I add that to the license? Just add a not in the README or what?

**Comment by SolarAquarion** [comment]
I suppose?

**Comment by PorygonZRocks** [comment]
I've added the themes back. There are a few issues (key popup, suggestions, Light theme has shadowed keys for some reason), but otherwise it works (and I did add all the files this time ;).

**Comment by PorygonZRocks** [comment]
New PR at https://github.com/klausw/hackerskeyboard/pull/602

**Comment by klausw** [comment]
Thank you for the contribution, and sorry about the long delay in merging it. The latest 1.40.6 should fix the shadowed keys in the light theme, but I had to make the key labels black instead of dark gray to make them match the fixed-color symbols. Personally I prefer it this way since the contrast is better :-)

**Pull request closed without merging**
