### PR TITLE
Add Esperanto accented characters

### LINKED ISSUE #524: Esperanto letters
Would it be possible to add the Esperanto alphabet letters to one of the layouts? Ideally just the internationalised/English one. The required letters are

'ĉ' [U+0109] - LATIN SMALL LETTER C WITH CIRCUMFLEX
'Ĉ' [U+0108] - LATIN CAPITAL LETTER C WITH CIRCUMFLEX

'ĝ' [U+011d] - LATIN SMALL LETTER G WITH CIRCUMFLEX
'Ĝ' [U+011c] - LATIN CAPITAL LETTER G WITH CIRCUMFLEX

'ĥ' [U+0125] - LATIN SMALL LETTER H WITH CIRCUMFLEX
'Ĥ' [U+0124] - LATIN CAPITAL LETTER H WITH CIRCUMFLEX

'ĵ' [U+0135] - LATIN SMALL LETTER J WITH CIRCUMFLEX
'Ĵ' [U+0134] - LATIN CAPITAL LETTER J WITH CIRCUMFLEX

'ŝ' [U+015d] - LATIN SMALL LETTER S WITH CIRCUMFLEX
'Ŝ' [U+015c] - LATIN CAPITAL LETTER S WITH CIRCUMFLEX

'ŭ' [U+016d] - LATIN SMALL LETTER U WITH BREVE
'Ŭ' [U+016c] - LATIN CAPITAL LETTER U WITH BREVE

Likely these could be added on the pop-out menus as you hold the unmodified versions of the letter keys, as with many of the other accented versions.

### PR DESCRIPTION
**Pull request by leonerd**
Fixes #524

### CODE REVIEW

**Comment by happysmash27** [comment]
Dankon! Ĉu ĝi estas tie: https://github.com/leonerd/hackerskeyboard?

**Comment by leonerd** [comment]
Jes, tiu estas la sama afero.

**Comment by leonerd** [comment]
Now with conflict fixed.

Any chance someone could look at and merge this? It just adds a few extra letters - should be simple enough.

**Comment by TPS** [comment]
@KlausW Please consider this very small, rather useful PR. 🙇

**Comment by happysmash27** [comment]
Can this *please* be merged? I thought this project was abandoned with this wait time, yet there was still an update, and now I have to re-compile the entire thing again, remoting in from my phone too!

**Comment by happysmash27** [comment]
Thank you so much :D !

**Comment by klausw** [comment]
Sorry about the delay, I've been neglecting the project. Trying to find
some time to collect outstanding pull requests and issues to make a new
release.

**Pull request merged**
