### PR TITLE
German users may look for „Gänsefüßchen“.

### PR DESCRIPTION
**Pull request by ascherer**

### CODE REVIEW

**Comment by TPS** [comment]
From https://github.com/klausw/hackerskeyboard/issues/571 (summary):

Any interest in the rest of <kbd>“</kbd>,<kbd>”</kbd>,<kbd>„</kbd>,<kbd>‟</kbd>,<kbd>⹂</kbd>,<kbd>"</kbd>,<kbd>'</kbd>,<kbd>‘</kbd>,<kbd>’</kbd>,<kbd>‚</kbd>, & <kbd>‛</kbd> that's not included?

Also, could this be extended to "5-row ___US___ layout," as well?

**Comment by ascherer** [comment]
Sure, I’d like that (and I’m using both the German and the English layout from time to time).

Two minor issues, though:
1) Android 6 (or Github on Marshmallow) seems to have a system font with incomplete/broken “specials”.
2) A quick glance at the French layout doesn’t show the «guillemets» nor the other “quotation marks”.

**Comment by TPS** [comment]
In the US layout, <kbd>«</kbd><kbd>»</kbd> is in <kbd>\<</kbd><kbd>\></kbd>.  Incorrect for French layout?

**Comment by ascherer** [comment]
No, in the French layout all I find on the '**<**' key is '>', '≤', and '≥'. The German layout extends '**<**' with the mathematical comparators, the (single and double) guillemets, and the vertical bar. The English layout has the left-pointing comparators and guillemets on the '**,**' key and the right-pointing comparators and guillemets on the '**.**' key.

**Comment by TPS** [comment]
Whoops!  I have all the hints enabled on my keys.  Fixed above.

That French layout _might_ need work, then.  According to https://en.m.wikipedia.org/wiki/AZERTY#Guillemets_.22.C2.AB.22_and_.22.C2.BB.22 , they should be on <kbd>[</kbd><kbd>]</kbd>.  Are they _there_?

**Comment by ascherer** [comment]
No, '[' is on '**(**', together with '5', '–', and '5 over 8'. ']' is on '**)**', together with '°', '≈', and '≠'.

**Comment by TPS** [comment]
Strange.  Your call, then, where you want to put them.  According to same wiki, be aware different French layouts exist (though maybe not in HK), & may each have them in different keys.

**Comment by TPS** [comment]
@ascherer If you want this merged, the dev is in a rare maintenance mode, so polish this (i.e., fix conflict above) NOW, & then ping @ KlausW when done.

**Comment by ascherer** [comment]
@klausw Done as requested.

**Comment by TPS** [comment]
@KlausW Another simple PR that shouldn't take >1 min of your attention. 🙇

**Comment by TPS** [comment]
Thanks, @ascherer & @klausw! 🙇

**Pull request merged**
