### PR TITLE
Created Workman Layout

### PR DESCRIPTION
**Pull request by joel0**
Created a Workman keyboard layout.  Idea by @gooddadmike at https://github.com/ojbucao/Workman/issues/26.

https://github.com/ojbucao/workman

### CODE REVIEW

**Comment by klausw** [comment]
I'd like to merge this one - currently there's a merge conflict so I can't do so from the web UI. I can resolve this manually, but that may take some time.

**Comment by klausw** [comment]
Thanks! Merged after fixing up a leftover conflict, not tested yet.

**Comment by joel0** [comment]
I tested, and it looks like there's a problem (uses QWERTY instead of Workman).  I can take a look eventually.  I expect it has something to do with files being moved since my initial PR.

**Comment by klausw** [comment]
Argh, yes. The resource files need to go to app/src/main/res/ instead of java/res.

**Comment by joel0** [comment]
#745 supersedes this PR.  Thanks @Autotonic!

**Pull request closed without merging**
